CHROMIUM: MALI: Fix build error/warning due to unused variable
Mali builds may fail with -Werror as follows if CONFIG_DEVFREQ_THERMAL
is not enabled.

drivers/gpu/arm/midgard/backend/gpu/mali_kbase_devfreq.c:127:18: error: unused
variable 'df'

BUG=chrome-os-partner:58785
TEST=Build MALI enabled image with DEVFREQ_THERMAL disabled

Change-Id: I96265600f5b2fee4d08f82f326120305f737a850
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/400647
Reviewed-by: Daniel Kurtz <djkurtz@chromium.org>

Signed-off-by: Wadim Egorov <w.egorov@phytec.de>