CHROMIUM: MALI_MIDGARD: Mark as BROKEN
Build failure is

drivers/gpu/arm/midgard/mali_kbase_core_linux.c:
	In function 'kbase_platform_device_probe':
drivers/gpu/arm/midgard/mali_kbase_core_linux.c:3701:2: error:
	implicit declaration of function 'of_init_opp_table'

There is no such function in the Linux 4.4 kernel.

Note that this is just one of many build errors seen if MALI_MIDGARD
is enabled.

BUG=none
TEST='make ARCH=arm allmodconfig' passes

Change-Id: I7ee881e53a87561e0a5c1f27814c61765525b25d
Fixes: d4ca48691257 ("CHROMIUM: MALI: Wk51_2015 r9p0-15wk51 TX011 DDK")
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/342466
Commit-Ready: Guenter Roeck <groeck@google.com>
Tested-by: Guenter Roeck <groeck@google.com>
Reviewed-by: Stéphane Marchesin <marcheu@chromium.org>
Reviewed-by: Brian Norris <briannorris@chromium.org>

Signed-off-by: Wadim Egorov <w.egorov@phytec.de>