CHROMIUM: MALI: fixes the build error in linux kernel4.4
The build will be failure on chromeos kernel4.4
if you enable the MALI_MIDGARD.

drivers/gpu/arm/midgard/mali_kbase_core_linux.c:3701:2:
error: implicit declaration of function 'of_init_opp_table' [-Werror=implicit-function-declaration]
  if (of_init_opp_table(kbdev->dev) < 0)
    ^
drivers/gpu/arm/midgard/mali_kbase_core_linux.c:3742:2:
error: implicit declaration of function 'of_free_opp_table' [-Werror=implicit-function-declaration]
  of_free_opp_table(kbdev->dev);

Since the linux kernel4.4 had changed the PM / OPP API.
As the commit 8f8d37b2537a
"PM / OPP: Prefix exported opp routines with dev_pm_opp_"

BUG=chrome-os-partner:51368
TEST=Build on kevin board.

Change-Id: If900d66e8c6ab8b2f8df4bd48adcf3f552a92733
Signed-off-by: Caesar Wang <wxt@rock-chips.com>
Reviewed-on: https://chromium-review.googlesource.com/346373
Commit-Ready: Guenter Roeck <groeck@chromium.org>
Tested-by: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Guenter Roeck <groeck@chromium.org>

Signed-off-by: Wadim Egorov <w.egorov@phytec.de>