CHROMIUM: MALI: fix build error with !CONFIG_MALI_MIDGARD_DVFS
The stub function should be declared 'static inline' to prevent errors like this:

drivers/gpu/arm/midgard/mali_kbase_gpuprops.o: In function `kbase_rk_dvfs_utilisation':
drivers/gpu/arm/midgard/platform/rk/mali_kbase_rk_dvfs.h:63: multiple definition of `kbase_rk_dvfs_utilisation'
drivers/gpu/arm/midgard/mali_kbase_device.o:drivers/gpu/arm/midgard/platform/rk/mali_kbase_rk_dvfs.h:63: first defined here

BUG=chrome-os-partner:51368
TEST=build with CONFIG_MALI_DEVFREQ, instead of CONFIG_MALI_MIDGARD_DVFS

Change-Id: Ie36f3e228e31d34091c64121d497ebefaa120c7f
Signed-off-by: Brian Norris <briannorris@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/348055
Reviewed-by: Guenter Roeck <groeck@chromium.org>