CHROMIUM: MALI: adjust code for thermal devfreq on kernel 4.4
The driver will compile some errors if we enable the devfreq for IPA.

This patch as the following change:
(1) fixes the last_status caused the compile error.
(2) fixes the thermal temperature as the int type.
(3) "devfreq_cooling_power" instead of "devfreq_cooling_ops".
(4) "thermal_cooling_device" instead of "devfreq_cooling_device".
---

A detailed description as follows:
(1) fixes the last_status caused the compile error.
The driver will compile some errors if we enable the devfreq for IPA.
As the following:
drivers/gpu/arm/midgard/backend/gpu/mali_kbase_devfreq.c:137:33:
error: dereferencing pointer to incomplete type
   memcpy(&kbdev->devfreq_cooling->last_status, stat,

drivers/gpu/arm/midgard/backend/gpu/mali_kbase_devfreq.c:248:5:
error: passing argument 3 of 'of_devfreq_cooling_register_power' from
incompatible pointer type [-Werror]
        &power_model_simple_ops)

Since the last_status is included into devfreq, let's fix it on now.

(2) fixes the thermal temperature as the int type.
As the commit 17e8351
"thermal: consistently use int for temperatures" fixes the temperature
as the int type.

(3) "devfreq_cooling_power" instead of "devfreq_cooling_ops".

Obviously, the devfreq_cooling_ops is incorrect api.
Due to the api is suit for devfreq_cooling_power.
struct devfreq_cooling_power {
        unsigned long (*get_static_power)(unsigned long voltage);
        unsigned long (*get_dynamic_power)(unsigned long freq,
                        unsigned long voltage);
        unsigned long dyn_power_coeff;
};

(4) "thermal_cooling_device" instead of "devfreq_cooling_device".
Due to the of_devfreq_cooling_register_power() will return the
thermal_cooling_device.

Let's fix them on now.

BUG=chrome-os-partner:51368
TEST=tested the gpu for kevin
TEST=See the gpu devices on /sys/class/devfreq/ff9a0000.gpu
And probe the GPU success.
..
[2.482504] mali ff9a0000.gpu: GPU identified as 0x0860 r2p0 status 0
[2.508316] mali ff9a0000.gpu: Probed as mali0
..

Change-Id: Ic5f3947b032deaaa800ee316636a8cc61259ba5d
Signed-off-by: chenzhen <chenzhen@rock-chips.com>
Signed-off-by: Caesar Wang <wxt@rock-chips.com>
Reviewed-on: https://chromium-review.googlesource.com/346374
Commit-Ready: Guenter Roeck <groeck@chromium.org>
Tested-by: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Guenter Roeck <groeck@chromium.org>

Signed-off-by: Wadim Egorov <w.egorov@phytec.de>